### ISSUE TITLE
oneTrailAtATime not functional.

### ISSUE THREAD

**Issue by mibby** [JamieSinn/TrailGUI#19] opened 2015-06-27 08:52 UTC
TrailGUI dev 34

Users with access to more than one trail type are able to activate more than one trail at a time despite the setting being forced true.

```
#Whether or not the player can only have one trail at a time.
oneTrailAtATime: true

#Max number of concurrently equipped trails - Only used if the above is false - use 0 for no limit
maxActiveTrails: 0
```

And shouldn't the previous trail be removed and overridden when a user chooses another trail when oneTrailAtATime is enable?

**Comment by JamieSinn** [comment] 2015-06-27 15:14
Known. Not a bug. This will be fixed soon

**Closed as completed** 2015-07-06 00:00 UTC
Labels: low priority, in progress, not a bug
